# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

# Set vi mode
set -o vi

# Set the capacity of the history records
export HISTSIZE=10000
export HISTFILESIZE=20000

# Erase the duplicates of the history records
export HISTCONTROL=erasedups

# Share the history across multiple shells
shopt -s histappend
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Set some common directories, you can type `cd subdir` at any position, bash will automatically look `subdir` up in the subdirectories ot the path list of `CDPATH`
export CDPATH=".:~:~/workspace"

# Typing the directory name instead of prepending `cd` will automatically go into the directory
shopt -s autocd

# Revise typo 
shopt -s cdspell
